language: julia
os:
  - linux
julia:
  - 1.7
branches:
  only:
    - main
coveralls: true
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path-pwd()))'
        - julia --project-docs/ docs/make.jl
      after_success: skip